### ISSUE TITLE
Crankshaft failing to load from desktop mode

### ISSUE THREAD

**Issue by RogueLikely** [CrankshaftForSteam/crankshaft#2]
Running into an issue where Crankshaft often isn't loading when leaving desktop mode and returning to gaming mode (via the desktop shortcut).

**Comment by coolavery** [comment]
Hey, I adjusted the restart behaviour a bit in the 0.2.2 release, can you try going into the Crankshaft Settings menu, and toggle the autostart service off and on again? This will update the service to use the new behaviour.

Let me know if you still experience issues when returning to game mode after this change!

**Comment by coolavery** [comment]
Closing for now, feel free to re-open if you're still experiencing this issue.
