### ISSUE TITLE
Steam deck version mismatch

### ISSUE THREAD

**Issue by gpaulu** [CrankshaftForSteam/crankshaft#3]
`flatpak list` shows version `0.2.2` but in game mode the new condensed menu is not shown. Under `Crankshaft Settings` the Info section says version `0.2.1`.

**Comment by gpaulu** [comment]
I guess you have to reboot to upgrade crankshaft versions. After rebooting for the new steam os update, the crankshaft version is correct in game mode.

**Comment by coolavery** [comment]
Hi @gpaulu , thanks for the report, glad you got it to work! I'm going to see if I can have updates work without rebooting in the next version.
